version: '3'

services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: unless-stopped
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mediaserver/appdata/portainer:/data

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Adelaide
      - AUTO_UPDATE=true #optional
    volumes:
      - /mediaserver/appdata:/config
      - /mediaserver/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Adelaide
      - UMASK_SET=022 #optional
    volumes:
      - /mediaserver/appdata/radarr:/config
      - /mediaserver/media/movies:/movies
      - /mediaserver/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Adelaide
      - UMASK_SET=022 #optional
    volumes:
      - /mediaserver/appdata/sonarr:/config
      - /mediaserver/media/tv:/tv
      - /mediaserver/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Adelaide
      - UMASK_SET=022
      - WEBUI_PORT=8080
    volumes:
      - /mediaserver/appdata/qbittorrent:/config
      - /mediaserver/downloads:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8080:8080
    restart: unless-stopped

  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - /mediaserver/appdata/plex:/config
      - /mediaserver/media/tv:/tv
      - /mediaserver/media/movies:/movies
    restart: unless-stopped

  ombi:
    image: linuxserver/ombi
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Adelaide
    volumes:
      - /mediaserver/appdata/ombi:/config
    ports:
      - 3579:3579
    restart: unless-stopped
